function Tau_f = function_friction_CLS(in1)
%FUNCTION_FRICTION_CLS
%    TAU_F = FUNCTION_FRICTION_CLS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Sep-2022 10:32:16

dq1 = in1(:,1);
dq2 = in1(:,2);
dq3 = in1(:,3);
dq4 = in1(:,4);
dq5 = in1(:,5);
dq6 = in1(:,6);
dq7 = in1(:,7);
Tau_f = [dq1.*7.5516e-2+sign(dq1).*2.489e-1+7.1033e-2,dq2.*2.724e-1+sign(dq2).*3.404e-1-1.245e-1,dq3.*8.8615e-2+sign(dq3).*(8.9e+1./6.25e+2)+7.9248e-2,dq4.*2.492e-2+sign(dq4).*2.492e-2+2.4283e-2,dq5.*1.919e-1+sign(dq5).*2.513e-1+5.4213e-2,dq6.*1.919e-1+sign(dq6).*3.428e-1+2.5908e-2,dq7.*8.054799999999999e-2+sign(dq7).*1.217e-1+5.9953e-2];
